"""
    FixedAtomsProbabilityDistribution(s::FrankWolfe.ActiveSet)

Construct a distribution from the active set generated by a Frank-Wolfe algorithm.
"""
function FixedAtomsProbabilityDistribution(s::ActiveSet)
    return FixedAtomsProbabilityDistribution(s.atoms, s.weights)
end
